step 1) 데이터 불러서 한 행씩 출력하기

In [ ]:
import csv
f= open('/content/seoul.csv', 'r', encoding='cp949')  

data= csv.reader(f) 
header= next(data)  #헤더 추출

for row in data :
  print(row)
  #최고기온 데이터만 추출-> 결측치 때문에 오류발생-> 조건을 줘서 처리하기 위해 if문
  row[-1] =  float(row[-1])   #float(row[4]) ->제일 마지막 컬럼->-1로 인덱스 처리
 # ㄴ>변수에 다시 담아주는게 중요! row[-1]

f.close()

step 2) 데이터 중 최고 기온을 실수로 변환하여 한 행씩 출력하기

In [ ]:
import csv

max_temp = -999 #최고 기온 값을 저장할 변수, 명확한 결과를 위해 극적인 값으로 셋팅. 0으로 안함.
max_date = '' # 최고 기온이 가장 높았던 날짜를 저장하는 변수

f= open('/content/seoul.csv', 'r', encoding='cp949')  

data= csv.reader(f) 
header= next(data)  #헤더 추출

for row in data :
  #최고 기온 데이터가 '' 인지 확인 (결측치인지 확인)
  if row[-1] == '' :
    row[-1] =-999    #-999를 넣어서 빈 문자열('')이 있던 자리라고 표시
  
  row[-1] = float(row[-1]) #기온 데이터 실수형으로 변환
  print(row[0], row[-1])  #날짜 데이터와 같이 출력

f.close()

step 3) 최고 기온과 최고 기온이었던 날짜 찾기

In [12]:
import csv

max_temp = -999 #최고 기온 값을 저장할 변수, 명확한 결과를 위해 극적인 값으로 셋팅. 0으로 안함.
max_date = '' # 최고 기온이 가장 높았던 날짜를 저장하는 변수

f= open('/content/seoul.csv', 'r', encoding='cp949')  

data= csv.reader(f) 
header= next(data)  #헤더 추출

for row in data :
  #최고 기온 데이터가 '' 인지 확인 (결측치인지 확인)
  if row[-1] == '' :
    row[-1] =-999    #-999를 넣어서 빈 문자열('')이 있던 자리라고 표시
  
  row[-1] = float(row[-1]) #기온 데이터 실수형으로 변환

  #최고 기온 정보를 저장
  if max_temp < row[-1] :
    max_date = row[0]
    max_temp = row[-1]

f.close()

print('기상 관측 이래 서울의 최고 기온이 가장 높았던 날은', max_date+'로', max_temp, '도 였습니다.')

기상 관측 이래 서울의 최고 기온이 가장 높았던 날은 2018-08-01로 39.6 도 였습니다.

step4) 최저 기온과 최저 기온이었던 날짜 찾기

In [19]:
import csv

min_temp = 999 #누가봐도 최저기온 아닌 값 넣어줘. 최저 기온 값을 저장할 변수, 명확한 결과를 위해 극적인 값으로 셋팅. 0으로 안함.
min_date = '' # 최고 기온이 가장 높았던 날짜를 저장하는 변수

f= open('/content/seoul.csv', 'r', encoding='cp949')  

data= csv.reader(f) 
header= next(data)  #헤더 추출

for row in data :
  #최저 기온 데이터가 '' 인지 확인 (결측치인지 확인)
  if row[3] == '' :
    row[3] =999    #-999를 넣어서 빈 문자열('')이 있던 자리라고 표시
  
  row[3] = float(row[3]) #기온 데이터 실수형으로 변환

  #최저 기온 정보를 저장
  if min_temp > row[3] :
    min_date = row[0]
    min_temp = row[3]   #for문 안에서 최저온도 계속 비교

f.close()

print('기상 관측 이래 서울의 최저 기온이 가장 높았던 날은', min_date+'로', min_temp, '도 였습니다.')

기상 관측 이래 서울의 최저 기온이 가장 높았던 날은 1927-12-31로 -23.1 도 였습니다.

최고 기온 중에서 가장 온도가 낮았던 날짜와 온도는?

In [41]:
import csv
#-999로 해놓으면 밑에 for문 안에 아예 들어가지 못해서 -999가 나온다.
max_temp = 999 #최저 기온 값을 저장할 변수, 명확한 결과를 위해 극적인 값으로 셋팅. 0으로 안함.
max_date = '' # 최고 기온이 가장 높았던 날짜를 저장하는 변수

f= open('/content/seoul.csv', 'r', encoding='cp949')  

data= csv.reader(f) 
header= next(data)  #헤더 추출

for row in data :
  #최저 기온 데이터가 '' 인지 확인 (결측치인지 확인)
  if row[-1] == '' :
    row[-1] =999    #-999를 넣어서 빈 문자열('')이 있던 자리라고 표시
  
  row[-1] = float(row[-1]) #기온 데이터 실수형으로 변환

  #최저 기온 정보를 저장
  if max_temp > row[-1] :
    max_date = row[0]
    max_temp = row[-1]   #for문 안에서 최저온도 계속 비교

f.close()

print('기상 관측 이래 서울의 최고 기온이 가장 낮았던 날은', max_date+'로', max_temp, '도 였습니다.')

기상 관측 이래 서울의 최고 기온이 가장 낮았던 날은 1915-01-13로 -16.3 도 였습니다.